version: '3'

services:
  mywell-server:
    image: lewisdaly/mywell-server:${VERSION_NUMBER}_${TRAVIS_BUILD_NUMBER}
    ports:
     - "${SERVER_PORT}:3000"
    environment:
      - "TERM=xterm-256color"
      - ENABLE_NOTIFICATIONS
      - DB_HOST
      - DB_NAME
      - DB_PASSWORD
      - DB_USER
      - TWILIO_ACCOUNT_SID
      - TWILIO_AUTH_TOKEN
      - TWILIO_PHONE_NUMBER
    networks:
      - base-network
    deploy:
      labels:
        - "traefik.port=3000"
        - "traefik.docker.network=base-network"
        - "traefik.frontend.rule=Host:${STAGE_PREFIX}mywell-server.marvi.org.in"
        - "traefik.protocol=http"

  mywell-ui:
    image: lewisdaly/mywell-ui:${VERSION_NUMBER}_${TRAVIS_BUILD_NUMBER}
    ports:
     - "${UI_PORT}:80"
    command: /usr/src/app/entrypoint.sh
    environment:
      - ENVIRONMENT=${STAGE}
      - SERVER_URL
      - ENABLE_LOGS
      - VERSION_NUMBER
    networks:
      - base-network
    deploy:
      labels:
        - "traefik.port=80"
        - "traefik.docker.network=base-network"
        - "traefik.frontend.rule=Host:${STAGE_PREFIX}mywell.marvi.org.in"
        - "traefik.protocol=http"

  mywell-utils:
    image: lewisdaly/mywell-utils:${VERSION_NUMBER}_${TRAVIS_BUILD_NUMBER}
    environment:
      - SEED_FILE_PATH=s3://mywell-deployment/restore/mywell_2017-06-253:12:22.sql
      - DB_HOST
      - DB_NAME
      - DB_PASSWORD
      - DB_USER
      - DONE_SEEDING_SUFFIX
    networks:
      - base-network

volumes:
  db-data:

networks:
  base-network:
    external: true
