version: '3'

services:
  mywell-server:
    image: lewisdaly/mywell-server:${IMAGE_SUFFIX}
    ports:
     - "3000:3000"
    environment:
      - "TERM=xterm-256color"
      - ENABLE_NOTIFICATIONS=false
      - DB_HOST
      - DB_NAME
      - DB_PASSWORD
      - DB_USER
      - TWILIO_ACCOUNT_SID
      - TWILIO_AUTH_TOKEN
      - TWILIO_PHONE_NUMBER
    networks:
      - base-network
    deploy:
      labels:
        - "traefik.port=3000"
        - "traefik.docker.network=base-network"
        - "traefik.frontend.rule=Host:${STAGE_PREFIX}mywell-server.vessels.tech"
        - "traefik.protocol=http"

  mywell-ui:
    image: lewisdaly/mywell-ui:${IMAGE_SUFFIX}
    ports:
     - "8000:80"
    command: /usr/src/app/entrypoint.sh
    environment:
      - ENVIRONMENT=development
      - SERVER_URL
      - ENABLE_LOGS=true
      - VERSION_NUMBER=dev_1.3.1
    networks:
      - base-network
    deploy:
      labels:
        - "traefik.port=80"
        - "traefik.docker.network=base-network"
        - "traefik.frontend.rule=Host:${STAGE_PREFIX}mywell.vessels.tech"
        - "traefik.protocol=http"

  mywell-utils:
    image: lewisdaly/mywell-utils:${IMAGE_SUFFIX}
    environment:
      - SEED_FILE_PATH=s3://mywell-deployment/restore/mywell_2017-06-143:06:49.sql
      - DB_HOST
      - DB_NAME
      - DB_PASSWORD
      - DB_USER
    networks:
      - base-network

volumes:
  db-data:

networks:
  base-network:
    external: true
