version: '3'

services:
  mywell-server:
    image: lewisdaly/mywell-server:dev_1.3.1
    ports:
     - "3000:3000"
    environment:
      - "TERM=xterm-256color"
      - ENABLE_NOTIFICATIONS=false
      - DB_HOST
      - DB_NAME
      - DB_PASSWORD
      - DB_USER
    networks:
      - base-network
    deploy:
      labels:
        - "traefik.port=3000"
        - "traefik.docker.network=base-network"
        - "traefik.frontend.rule=Host:mywell-server.vessels.tech"
        - "traefik.protocol=http"

  mywell-ui:
    image: lewisdaly/mywell-ui:dev_1.3.1
    ports:
     - "8000:80"
    command: /usr/src/app/entrypoint.sh
    environment:
      - ENVIRONMENT=development
      - SERVER_URL=https://mywell-server.vessels.tech
      - ENABLE_LOGS=true
      - VERSION_NUMBER=dev_1.3.1
    networks:
      - base-network
    deploy:
      labels:
        - "traefik.port=80"
        - "traefik.docker.network=base-network"
        - "traefik.frontend.rule=Host:mywell.vessels.tech"
        - "traefik.protocol=http"

  mywell-utils:
    image: lewisdaly/mywell-utils:latest
    environment:
      - SEED_FILE_PATH=s3://mywell-deployment/mywell_2017-03-070-20-08.sql
      - DB_HOST
      - DB_NAME
      - DB_PASSWORD
      - DB_USER
    networks:
      - base-network

volumes:
  db-data:

networks:
  base-network:
    external: true
