version: '3'

services:
  mywell-server:
    image: lewisdaly/mywell-server:${VERSION_NUMBER}_${TRAVIS_BUILD_NUMBER}
    ports:
     - "${SERVER_PORT}:3000"
    environment:
      - "TERM=xterm-256color"
      - ENABLE_NOTIFICATIONS
      - DB_HOST
      - DB_NAME
      - DB_PASSWORD
      - DB_USER
      - TWILIO_ACCOUNT_SID
      - TWILIO_AUTH_TOKEN
      - TWILIO_PHONE_NUMBER
      - SMS_HORIZON_USER
      - SMS_HORIZON_KEY
    networks:
      - base-network
    deploy:
      labels:
        - "traefik.port=3000"
        - "traefik.docker.network=base-network"
        - "traefik.frontend.rule=${TEMP_SERVER_FRONTEND_RULE}"
        - "traefik.protocol=http"
      resources:
        limits:
          memory: 350M
        reservations:
          memory: 200M
      # restart_policy:
      #   condition: on-failure
      #   delay: 5s
      #   max_attempts: 3
      #   window: 120s

  #No longer using - using static website hosting instead!
  # mywell-ui:
  #   image: lewisdaly/mywell-ui:${VERSION_NUMBER}_${TRAVIS_BUILD_NUMBER}
  #   ports:
  #    - "${UI_PORT}:80"
  #   environment:
  #     - ENVIRONMENT=${STAGE}
  #     - SERVER_URL
  #     - ENABLE_LOGS
  #     - VERSION_NUMBER
  #     - REACT_APP_GRAPHQL_ENDPOINT
  #     - GQL_URL=${REACT_APP_GRAPHQL_ENDPOINT}
  #     - PORT=80
  #   networks:
  #     - base-network
  #   deploy:
  #     labels:
  #       - "traefik.port=80"
  #       - "traefik.docker.network=base-network"
  #       - "traefik.frontend.rule=Host:${STAGE_PREFIX}mywell.marvi.org.in"
  #       - "traefik.protocol=http"


  mywell-gql:
    image: lewisdaly/mywell-gql:${VERSION_NUMBER}_${TRAVIS_BUILD_NUMBER}
    environment:
      - PORT=3001
      - DB_HOST
      - DB_NAME
      - DB_PASSWORD
      - DB_USER
    networks:
      - base-network
    links:
      - db:db
    ports:
      - 3001:3001
    deploy:
      labels:
        - "traefik.port=3001"
        - "traefik.docker.network=base-network"
        - "traefik.frontend.rule=Host:${STAGE_PREFIX}mywell-gql.marvi.org.in"
        - "traefik.protocol=http"

  mywell-utils:
    image: lewisdaly/mywell-utils:${VERSION_NUMBER}_${TRAVIS_BUILD_NUMBER}
    environment:
      - SEED_FILE_PATH=s3://mywell-deployment/restore/mywell_2017-06-253:12:22.sql
      - DB_HOST
      - DB_NAME
      - DB_PASSWORD
      - DB_USER
      - DONE_SEEDING_SUFFIX
    networks:
      - base-network
    # deploy:
      # resources:
      #   limits:
      #     memory: 50M
      #   reservations:
      #     memory: 10M

volumes:
  db-data:

networks:
  base-network:
    external: true
