sudo: required
language: nodejs
node_js:
- 6
services:
- docker
script:
- echo "Hello"
after_success:
- source ./deployment/tools/stage_calculator.sh;
- source ./env/env$STAGE.sh;
- cd ./deployment && ./run-tools.sh deploy
before_install:
- openssl aes-256-cbc -K $encrypted_5d1e44ff4222_key -iv $encrypted_5d1e44ff4222_iv
  -in secrets.tar.enc -out secrets.tar -d;
- tar xvf secrets.tar;
