sudo: required
language: nodejs
node_js:
- 6
services:
- docker
script: 
after_success:
- export STAGE=development;
- source ./env/env$STAGE.sh;
- source ./env/envdeployment.sh;
- export DEPLOYMENT_DIR="`pwd`/deployment";
- "./deployment/tools/ssh_tunnel.sh;"
- "./deployment/_up.sh;"
before_install:
- openssl aes-256-cbc -K $encrypted_5d1e44ff4222_key -iv $encrypted_5d1e44ff4222_iv
  -in secrets.tar.enc -out secrets.tar -d
- openssl aes-256-cbc -K $encrypted_5d1e44ff4222_key -iv $encrypted_5d1e44ff4222_iv
  -in secrets.tar.enc -out secrets.tar -d;
- tar xvf secrets.tar;
- mkdir -p ~/.aws/keys;
- cp mywell-docker.pem ~/.aws/keys/mywell-docker.pem;
