sudo: required
language: nodejs
node_js:
  - 6
services:
  - docker
script:
  - docker-compose -f docker-compose.yml build
  # - docker-compose -f docker-compose.yml pull --ignore-pull-failures

  #TODO: run tests!
  # - docker-compose -f docker-compose.yml -f docker-compose.test.yml up -d sms-bot
  # - docker exec -it sms-bot bash -c "/usr/src/app/test/test.sh"
after_success:
  - if [ "$TRAVIS_BRANCH" == "develop" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      export STAGE=development;
      export IMAGE_SUFFIX=development;
      ./deployment/tools/tag_and_push_docker.sh skip-build;
    fi

  # TODO: remove '-test' once we have deployed properly
  - if [ "$TRAVIS_BRANCH" == "master-test" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      export STAGE=production;
      export IMAGE_SUFFIX=production;
      ./deployment/tools/tag_and_push_docker.sh skip-build;
    fi
