sudo: required
language: nodejs
node_js:
- 6
services:
- docker
script:
- docker-compose -f docker-compose.yml build
after_success:
- if [ "$TRAVIS_BRANCH" == "develop" ]; then docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  export STAGE=development; export IMAGE_SUFFIX=development; ./deployment/tools/tag_and_push_docker.sh
  skip-build; fi
- if [ "$TRAVIS_BRANCH" == "master" ]; then docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  export STAGE=production; export IMAGE_SUFFIX=production; ./deployment/tools/tag_and_push_docker.sh
  skip-build; fi
before_install:
- openssl aes-256-cbc -K $encrypted_5d1e44ff4222_key -iv $encrypted_5d1e44ff4222_iv
  -in mywell-docker.pem.enc -out ~\/.aws/keys/mywell-docker.pem -d
