#TODO: A docker compose file whice refers to the built docker images, and doesn't build them itself

version: '2'
services:
  mywell-gql:
    container_name: mywell-gql
    image: ldaly/mywell-gql:latest
    ports:
      - 3001:3001
    # volumes:
      # - ./mywell-gql/:/usr/src/app/
    environment:
      - PORT=3001
      - DB_HOST
      - DB_NAME
      - DB_PASSWORD
      - DB_USER
    links:
      - db:db
    command: "npm run local"
    labels:
      - "traefik.port=3001"
      - "traefik.docker.network=base-network"
      - "traefik.frontend.rule=Host:${STAGE_PREFIX}mywell-gql.vessels.tech"
      - "traefik.protocol=http"

  mywell-utils:
    container_name: mywell-utils
    image: ldaly/mywell-utils:latest
    command: tail -f /dev/null

  mywell-server:
    container_name: mywell-server
    image: ldaly/mywell-server:latest
    ports:
     - "3000:3000"
    command: "nodemon -L ."
    environment:
      - "TERM=xterm-256color"
      - VIRTUAL_HOST=mywell-server.marvi.org.in
      - HTTPS_METHOD=redirect
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_EMAIL=lewis@vesselstech.com
      - LETSENCRYPT_HOST=mywell-server.marvi.org.in
      - ENABLE_NOTIFICATIONS
      - DB_HOST
      - DB_NAME
      - DB_PASSWORD
      - DB_USER
      - TWILIO_ACCOUNT_SID
      - TWILIO_AUTH_TOKEN
      - TWILIO_PHONE_NUMBER
      - SMS_HORIZON_USER
      - SMS_HORIZON_KEY
      - AWS_PROFILE=vessels-lewis.daly
      - FIREBASE_BASE_URL
      - OUR_WATER_ORG_ID
      - REACT_APP_FB_API_KEY
      - REACT_APP_FB_AUTH_DOMAIN
      - REACT_APP_FB_DATABASE_URL
      - REACT_APP_FB_PROJECT_ID
      - REACT_APP_FB_STORAGE_BUCKET
    links:
      - db:db
    labels:
      - "traefik.port=3000"
      - "traefik.docker.network=base-network"
      - "traefik.frontend.rule=${TEMP_SERVER_FRONTEND_RULE}"
      - "traefik.protocol=http"

  mywell-ui:
    container_name: mywell-ui
    image: ldaly/mywell-ui:latest
    ports:
      - 8080:80
    command: "./build_and_run.sh"
    environment:
      - VIRTUAL_HOST=mywell.marvi.org.in
      - HTTPS_METHOD=redirect
      - VIRTUAL_PORT=80
      #Tells nodemon server which port we are looking for
      - PORT=80
      - LETSENCRYPT_EMAIL=lewis@vesselstech.com
      - LETSENCRYPT_HOST=mywell.marvi.org.in
      - ENVIRONMENT
      - ENABLE_LOGS
      - VERSION_NUMBER
      - SERVER_URL
      - REACT_APP_GRAPHQL_ENDPOINT
      - UI_BUCKET_NAME
      - REACT_APP_FB_API_KEY
      - REACT_APP_FB_AUTH_DOMAIN
      - REACT_APP_FB_DATABASE_URL
      - REACT_APP_FB_PROJECT_ID
      - REACT_APP_FB_STORAGE_BUCKET
    labels:
      - "traefik.port=80"
      - "traefik.docker.network=base-network"
      - "traefik.frontend.rule=Host:mywell-server.vessels.tech,${STAGE_PREFIX}mywell.marvi.org.in"
      - "traefik.protocol=http"

  db:
    container_name: mywell-db
    image: mariadb:10.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mywell
      - MYSQL_USER=mywell
      - MYSQL_PASSWORD=password
    expose:
      - 3306
    volumes:
      - ./mywell-db/server/boot/db:/docker-entrypoint-initdb.d

  traefik:
    image: traefik:1.3.0
    ports:
      - 80:80
      - 443:443
      - 8081:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/tmp:/etc/traefik/acme
    command: >-
      --entryPoints='Name:http Address::80' \
      --entryPoints='Name:https Address::443 TLS' \
      --defaultEntryPoints=http,https \
      --acme.entryPoint=https \
      --acme.email=lewis@vesselstech.com \
      --acme.storage=/etc/traefik/acme/acme.json \
      --acme.domains=marvi.org.in \
      --acme.onHostRule=true \
      --docker \
      --docker.swarmmode \
      --docker.domain=marvi.org.in \
      --docker.watch \
      --logLevel=ERROR \
      --web
