version: '2'
services:
  mywell-server:
    build: ./mywell-server/
    ports:
     - "3000:3000"
    volumes:
     - ./mywell-server:/usr/src/app
    links:
    - db:db

  mywell-ui:
    build: ./mywell-ui/
    ports:
     - "80:80"
    volumes:
     - ./mywell-ui:/usr/src/app
    command: npm run prod

  db:
    image: mariadb:10.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mywell
      - MYSQL_USER=mywell
      - MYSQL_PASSWORD=password
    expose:
      - 3306
    volumes:
      - ./app/server/boot/db:/docker-entrypoint-initdb.d
