version: '2'
services:
  mywell-console:
    container_name: mywell-console
    build: ./mywell-console/
    image: mywell-console:local
    ports:
      - 3002:3000
    volumes:
      - ./mywell-console:/usr/src/app
      - ./mywell-console/node_modules:/usr/src/app/node_modules
    environment:
      - REACT_APP_GRAPHQL_ENDPOINT
    # command: tail -f /dev/null

  mywell-gql:
    container_name: mywell-gql
    build: ./mywell-gql/
    image: mywell-gql:local
    ports:
      - 3001:3001
    volumes:
      - ./mywell-gql/:/usr/src/app/
    environment:
      - PORT=3001
      - DB_HOST
      - DB_NAME
      - DB_PASSWORD
      - DB_USER
    links:
      - db:db
    command: "npm run local"

  mywell-utils:
    container_name: mywell-utils
    build: ./mywell-utils/
    image: mywell-utils:local
    command: tail -f /dev/null

  mywell-server:
    container_name: mywell-server
    build: ./mywell-server/
    image: mywell-server:local
    ports:
     - "3000:3000"
    volumes:
     - ./mywell-server:/usr/src/app
     - ./mywell-server/node_modules:/usr/src/app/node_modules
     - ~/.aws:/root/.aws
    command: "nodemon -L ."
    environment:
      - "TERM=xterm-256color"
      - VIRTUAL_HOST=mywell-server.marvi.org.in
      - HTTPS_METHOD=redirect
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_EMAIL=lewis@vesselstech.com
      - LETSENCRYPT_HOST=mywell-server.marvi.org.in
      - ENABLE_NOTIFICATIONS
      - DB_HOST
      - DB_NAME
      - DB_PASSWORD
      - DB_USER
      - TWILIO_ACCOUNT_SID
      - TWILIO_AUTH_TOKEN
      - TWILIO_PHONE_NUMBER
      - SMS_HORIZON_USER
      - SMS_HORIZON_KEY
      - AWS_PROFILE=vessels-lewis.daly
    links:
      - db:db

  mywell-ui:
    container_name: mywell-ui
    build: ./mywell-ui/
    image: mywell-ui:local
    ports:
     - "8080:80"
    volumes:
     - ./mywell-ui:/usr/src/app
    command: npm run dev
    environment:
      - VIRTUAL_HOST=mywell.marvi.org.in
      - HTTPS_METHOD=redirect
      - VIRTUAL_PORT=80
      - PORT=80
      - LETSENCRYPT_EMAIL=lewis@vesselstech.com
      - LETSENCRYPT_HOST=mywell.marvi.org.in
      - ENVIRONMENT
      - ENABLE_LOGS
      - VERSION_NUMBER

  db:
    container_name: mywell-db
    image: mariadb:10.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mywell
      - MYSQL_USER=mywell
      - MYSQL_PASSWORD=password
    expose:
      - 3306
    volumes:
      - ./mywell-db/server/boot/db:/docker-entrypoint-initdb.d
