version: '2'
services:
  mywell-console:
    container_name: mywell-console
    build: ./mywell-console/
    image: mywell-console:local
    ports:
      - 3002:3000
    volumes:
      - ./mywell-console:/usr/src/app
      - ./mywell-console/node_modules:/usr/src/app/node_modules
    environment:
      - REACT_APP_GRAPHQL_ENDPOINT
    # command: tail -f /dev/null

  mywell-gql:
    container_name: mywell-gql
    build: ./mywell-gql/
    image: mywell-gql:local
    ports:
      - 3001:3001
    volumes:
      - ./mywell-gql/:/usr/src/app/
    environment:
      - PORT=3001
      - DB_HOST
      - DB_NAME
      - DB_PASSWORD
      - DB_USER
    links:
      - db:db
    command: "npm run local"

  mywell-utils:
    container_name: mywell-utils
    build: ./mywell-utils/
    image: mywell-utils:local
    command: tail -f /dev/null

  db:
    container_name: mywell-db
    image: mariadb:10.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mywell
      - MYSQL_USER=mywell
      - MYSQL_PASSWORD=password
    expose:
      - 3306
    volumes:
      - ./mywell-db/server/boot/db:/docker-entrypoint-initdb.d
