version: '3'

services:
  traefik:
    image: traefik:1.3.0
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    networks:
      - base-network
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: /var/tmp
        target: /etc/traefik/acme
    deploy:
      placement:
        constraints:
          - node.role == manager
    command: >-
      --entryPoints='Name:http Address::80 Redirect.EntryPoint:https' \
      --entryPoints='Name:https Address::443 TLS' \
      --defaultEntryPoints=http,https \
      --acme.entryPoint=https \
      --acme.email=lewis@vesselstech.com \
      --acme.storage=/etc/traefik/acme/acme.json \
      --acme.domains=vessels.tech \
      --acme.onHostRule=true \
      --docker \
      --docker.swarmmode \
      --docker.domain=vessels.tech \
      --docker.watch \
      --logLevel=DEBUG \
      --web

  viz:
    image: dockersamples/visualizer
    ports:
      - 8081:8080
    deploy:
      placement:
        constraints:
          - node.role == manager
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock

  portainer:
    image: portainer/portainer
    ports:
      - 9000:9000
    deploy:
      placement:
        constraints:
          - node.role == manager
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    command: -H unix:///var/run/docker.sock

networks:
  base-network:
