AWSTemplateFormatVersion: "2010-09-09"
Description: MyWell non docker resources stack
Resources:
  MyWellDatabase:
    Type: "AWS::RDS::DBInstance"
    Properties:
      AllocatedStorage: "10"
      BackupRetentionPeriod: "7"
      DBInstanceClass: "db.t2.micro"
      DBInstanceIdentifier: "mywelldb"
      Engine: MariaDB
      EngineVersion: 10.0.24
      MasterUsername: mywell
      MasterUserPassword: marvi-mywell
      MonitoringInterval: 0
      MultiAZ: false
      PubliclyAccessible: false
      StorageEncrypted: false
      Port: 3306
      DBSecurityGroups:
        - Ref: DbSecurityByEC2SecurityGroup

 #TODO: make refer to proper outputs from other stack
  DbSecurityByEC2SecurityGroup:
    Type: AWS::RDS::DBSecurityGroup
    Properties:
      GroupDescription: Ingress for Amazon EC2 security group
      EC2VpcId:
        Ref: vpc-8a89e8ee
      DBSecurityGroupIngress:
      - EC2SecurityGroupId: sg-18496a7f
        EC2SecurityGroupOwnerId: "745457803371"
  MyWellDeployment:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: mywell-deployment
