AWSTemplateFormatVersion: "2010-09-09"
Description: MyWell non docker resources stack
Resources:
  MyWellDatabase:
    Type: "AWS::RDS::DBInstance"
    Properties:
      AllocatedStorage: "10"
      BackupRetentionPeriod: "7"
      DBInstanceClass: "db.t2.micro"
      DBInstanceIdentifier: "mywelldb"
      Engine: MariaDB
      EngineVersion: 10.0.24
      MasterUsername: mywell
      MasterUserPassword: marvi-mywell
      MonitoringInterval: 0
      MultiAZ: false
      PubliclyAccessible: false
      StorageEncrypted: false
      Port: 3306
