AWSTemplateFormatVersion: "2010-09-09"
Description: MyWell non docker resources stack
Parameters:
  DockerStack:
    Description: The name of the docker stack
    Type: String
Resources:
  #TODO: make refer to proper outputs from other stack
  MyWellDBSubnetGroup:
    Type: "AWS::RDS::DBSubnetGroup"
    Properties:
      DBSubnetGroupDescription: "Subnets available for RDS"
      SubnetIds:
        - Fn::ImportValue:
            !Sub "${DockerStack}:PubSubnetAz1"
        - Fn::ImportValue:
            !Sub "${DockerStack}:PubSubnetAz2"
        - Fn::ImportValue:
            !Sub "${DockerStack}:PubSubnetAz3"

  DbSecurityByEC2SecurityGroup:
   Type: AWS::RDS::DBSecurityGroup
   Properties:
     GroupDescription: Ingress for Amazon EC2 security group
     EC2VpcId:
      Fn::ImportValue:
       !Sub "${DockerStack}:VPC"
     DBSecurityGroupIngress:
       - EC2SecurityGroupId:
          Fn::ImportValue:
            !Sub "${DockerStack}:SwarmWideSG"

  MyWellDatabase:
    DependsOn: DbSecurityByEC2SecurityGroup
    Type: "AWS::RDS::DBInstance"
    Properties:
      AllocatedStorage: "10"
      BackupRetentionPeriod: "7"
      DBInstanceClass: "db.t2.micro"
      DBInstanceIdentifier: "mywelldb"
      Engine: MariaDB
      EngineVersion: 10.0.24
      MasterUsername: mywell
      MasterUserPassword: marvi-mywell
      MonitoringInterval: 0
      MultiAZ: false
      PubliclyAccessible: false
      StorageEncrypted: false
      Port: 3306
      DBSubnetGroupName:
        Ref: MyWellDBSubnetGroup
      VPCSecurityGroups:
        -
          Ref: DbSecurityByEC2SecurityGroup


  MyWellDeployment:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: mywell-deployment
