version: '2'
services:
  mywell-server:
    image: lewisdaly/mywell-server:dev___VERSION_NUMBER__
    autoredeploy: true
    ports:
     - "3000:3000"
    volumes:
     - ./mywell-server:/usr/src/app
     - ./mywell-server/node_modules:/usr/src/app/node_modules
    environment:
      - TERM=xterm-256color
      - VIRTUAL_HOST=mywell-server.vesselstech.com
      - HTTPS_METHOD=redirect
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_EMAIL=lewis@vesselstech.com
      - LETSENCRYPT_HOST=mywell-server.vesselstech.com
      - ENABLE_NOTIFICATIONS=false
      - WAY2MINT_USR=__WAY2MINT_USR__
      - WAY2MINT_PWD=__WAY2MINT_PWD__
    links:
    - db:db

  mywell-ui:
    image: lewisdaly/mywell-server:dev___VERSION_NUMBER__
    autoredeploy: true
    ports:
     - "8080:80"
    volumes:
     - ./mywell-ui:/usr/src/app
    command: /usr/src/app/entrypoint.sh
    environment:
      - VIRTUAL_HOST=mywell.vesselstech.com
      - HTTPS_METHOD=redirect
      - VIRTUAL_PORT=80
      - LETSENCRYPT_EMAIL=lewis@vesselstech.com
      - LETSENCRYPT_HOST=mywell.vesselstech.com
      - ENVIRONMENT=production
      - ENABLE_LOGS=false
      - VERSION_NUMBER=__VERSION_NUMBER__
  db:
    image: mariadb:10.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mywell
      - MYSQL_USER=mywell
      - MYSQL_PASSWORD=password
    expose:
      - 3306
    volumes:
      - ./mywell-db/server/boot/db:/docker-entrypoint-initdb.d

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro
        - /certs:/etc/nginx/certs
        - /etc/nginx/vhost.d
        - /usr/share/nginx/html

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    volumes:
        - /var/run/docker.sock:/tmp/docker.sock:rw
        - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
        - nginx-proxy
    links:
        - nginx-proxy
