version: '2'
services:
  mywell-deploy:
    build: .
    container_name: mywell-deploy
    volumes:
      - ../env:/usr/src/env
      - ./:/usr/src/deploy
      - "~/.aws:/root/.aws"
      #static resources go here
      - /tmp/www:/tmp/www
    environment:
      - AWS_PROFILE
      - AWS_REGION
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - VERSION_NUMBER
      - MANAGER_NODE_DNS
      - DEFAULT_DNS_TARGET
      - STAGE
      - TRAVIS_BUILD_NUMBER
      - ENABLE_NOTIFICATIONS
      - DB_HOST
      - DB_NAME
      - DB_PASSWORD
      - DB_USER
      - DONE_SEEDING_SUFFIX
      - TWILIO_ACCOUNT_SID
      - TWILIO_AUTH_TOKEN
      - TWILIO_PHONE_NUMBER
      - SERVER_URL
      - ENABLE_LOGS
      - STAGE_PREFIX
      - UI_PORT
      - GQL_PORT
      - TEMP_SERVER_FRONTEND_RULE
      - REACT_APP_GRAPHQL_ENDPOINT
      - UI_BUCKET_NAME
      - WEBPACK_DEV
      - CONSOLE_DOMAIN_NAME
      - FIREBASE_BASE_URL
      - OUR_WATER_ORG_ID
    privileged: true
    command: /usr/src/deploy/tools/entrypoint.sh
