version: '3'

services:
  mywell-server:
    image: lewisdaly/mywell-server:dev_1.3.1
    ports:
     - "3000:3000"
    environment:
      - "TERM=xterm-256color"
      - VIRTUAL_HOST=dev.mywell-server.vessels.tech
      - HTTPS_METHOD=redirect
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_EMAIL=lewis@vessels.tech
      - LETSENCRYPT_HOST=dev.mywell-server.vessels.tech
      - ENABLE_NOTIFICATIONS-false
    depends_on:
      - mywell-db
    networks:
      - base-network
    deploy:
      labels:
        - "traefik.port=3000"
        - "traefik.docker.network=base-network"
        - "traefik.frontend.rule=Host:dev.mywell-server.vessels.tech"
        - "traefik.protocol=https"

  mywell-ui:
    image: lewisdaly/mywell-ui:dev_1.3.1
    ports:
     - "8000:80"
    command: /usr/src/app/entrypoint.sh
    environment:
      - VIRTUAL_HOST=dev.mywell.vessels.tech
      - HTTPS_METHOD=redirect
      - VIRTUAL_PORT=80
      - LETSENCRYPT_EMAIL=lewis@vesselstech.com
      - LETSENCRYPT_HOST=dev.mywell.vessels.tech
      - ENVIRONMENT=development
      - SERVER_URL=http://dev.mywell-server.vessels.tech
      - ENABLE_LOGS=true
      - VERSION_NUMBER=dev_1.3.1
    networks:
      - base-network
    deploy:
      labels:
        - "traefik.port=80"
        - "traefik.docker.network=base-network"
        - "traefik.frontend.rule=Host:dev.mywell.vessels.tech"
        - "traefik.protocol=https"

  mywell-db:
    image: mariadb:10.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mywell
      - MYSQL_USER=mywell
      - MYSQL_PASSWORD=password
    volumes:
      - db-data:/docker-entrypoint-initdb.d
    networks:
      - base-network

volumes:
  db-data:

networks:
  base-network:
    external: true
