version: '2'
services:
  mywell-deploy:
    build: .
    container_name: mywell-deploy
    volumes:
      - ../env:/usr/src/env
      - ./:/usr/src/deploy
      - "~/.aws:/root/.aws"
    environment:
      - AWS_PROFILE
      - AWS_REGION
      - VERSION_NUMBER
      - MANAGER_NODE_DNS
      - DEFAULT_DNS_TARGET
      - STAGE
      - TRAVIS_BUILD_NUMBER
    privileged: true
    command: /usr/src/deploy/tools/entrypoint.sh
